import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth-context";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
});

const playfair = Playfair_Display({
    subsets: ["latin"],
    variable: "--font-playfair",
});

export const metadata: Metadata = {
    title: "Appointment Booking Saas App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${manrope.variable} ${playfair.variable} antialiased`}>
                <AuthProvider>
                    <Navbar />
                    <main>{children}</main>
                    <Toaster toastOptions={{ classNames: { description: "!text-current !opacity-100" } }} position="top-center" />
                </AuthProvider>
            </body>
        </html>
    );
}
