import { Metadata } from "next";
import { CustomerContextProvider } from "./_components/customer-context";

export const metadata: Metadata = {
    title: "Appointment Booking Saas App",
    description: "Generated by create next app",
};

export default function CustomerLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <CustomerContextProvider>
            <main>{children}</main>
        </CustomerContextProvider>
    );
}
