import { Metadata } from "next";
import CustomersNavbar from "./_components/navbar";

export const metadata: Metadata = {
    title: "Appointment Booking Saas App",
    description: "Generated by create next app",
};

export default function CustomerLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <main>
            <CustomersNavbar />
            {children}
        </main>
    );
}
