import { Metadata } from "next";
export const metadata: Metadata = {
    title: "Appointment Booking Saas App",
    description: "Generated by create next app",
};

export default function PublicLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <main>
            {children}
        </main>
    );
}
